[project]
name = "gimnasio-rutinas"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "cursosiafundepos-create", email = "cursosiafundepos@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.3",
]

[project.scripts]
gimnasio-rutinas = "gimnasio_rutinas:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
